### ISSUE TITLE
option to limit the length of exception backtrace

### ISSUE THREAD

**Issue by ichylinux** [maedadev/bizside-ruby#39]
currently, audit_log#detect_exception_backtrace() collect all of the backtrace.

we are experiencing an issue to store audit log to elasticsearch.

elasticsearch denies a term with more than 32KB length, but sometimes our exception backtrace gets longer than that limit.

it would be great if the method interface accepts an option to truncate exception backtrace at the upper length.

**Comment by xketanaka** [comment]
We found that the "exception message" also exceeds the maximum length, fix it at #41

**Comment by ichylinux** [comment]
things were merged.
so i close this issue.
