### ISSUE TITLE
JobUtils#add_job_to fails with file object

### ISSUE THREAD

**Issue by ichylinux** [maedadev/bizside-ruby#46]
if JobUtils#add_job_to() is called with binary arguments, it raises error because of Marshal.dump/load is used.

document for Marshal states...

https://docs.ruby-lang.org/ja/latest/class/Marshal.html

```
ファイルに書き出せないオブジェクトをファイルに書き出そうとすると例外 [TypeError](https://docs.ruby-lang.org/ja/latest/class/TypeError.html) が発生します。ファイルに書き出せないオブジェクトは以下の通りです。
...
...
システムがオブジェクトの状態を保持するもの。具体的には以下のイン スタンス。Dir, File::Stat, IO とそのサブクラス File, Socket など。
```

**Comment by y-sugawara-acs** [comment]
Thank you for the fix. I added some tiny changes and merged.
